`define	dmfps       1
`define	dmtps       2
`define	dspl        3
`define	dsub        4
`define dtrap       5
`define	demt        6
`define	dsob        7
`define	dexor       8
`define	dadd        9
`define dbis        10
`define	dbic        11
`define	dbit        12
`define	dcmp        13
`define	dmov        14
`define dsxt        15
`define	dmtpi       16
`define	dmfpi       17
`define	dmark       18
`define	dasl        19
`define dasr        20
`define	drol        21
`define	dror        22
`define	dtst        23
`define	dsbc        24
`define dadc        25
`define	dneg        26
`define	ddec        27
`define	dinc        28
`define	dcom        29
`define dclr        30
`define	djsr        31
`define	dswab       32
`define	dnop        33
`define	drts        34
`define djmp        35
`define	drtt        36
`define	dreset      37
`define	diot        38
`define	dbpt        39
`define drti        40
`define	diwait      41
`define	dhalt       42

`define IDC_NOPS    42
